//
//  MainNetworkManagerMock.swift
//  JuniorTask
//
//  Created by Maksymilian Stan on 31/10/2024.
//

import Foundation

class MainNetworkManagerMock: NetworkManager {
    override func getNextURL() -> String? {
        nil
    }
    
    override func getAllEvents(_ session: URLSession = URLSession.shared, sortOption: SortOption?) async throws -> [EventResponse.Embedded.Event] {
        
        return [
            EventResponse.Embedded.Event(id: "1", name: "Strażak Sam Na Żywo - Przygoda Na Biwaku", images: [EventResponse.Embedded.Event.EventImage(ratio: "16_9", url: URL(string: "https://s1.ticketm.net/dam/a/dd5/d7a9ceee-bde3-4e84-a35f-b257044c4dd5_RECOMENDATION_16_9.jpg")!, width: 300, height: 200), EventResponse.Embedded.Event.EventImage(ratio: "", url: URL(string: "www.w.en/2kjfsaldkjf-sadf-asd-asdf_SOURCE.jpg")!, width: 500, height: 700), EventResponse.Embedded.Event.EventImage(ratio: "", url: URL(string: "www.w.en/2kjfsaldkjf-sadf-asd-fas_RECOMENDATION.jpg")!, width: 100, height: 150)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Warszawska 1"))])),
            EventResponse.Embedded.Event(id: "2", name: "China Moses - jazzowo-soulowe serce", images: [EventResponse.Embedded.Event.EventImage(ratio: "16_9", url: URL(string: "noURL")!, width: 300, height: 200)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Warszawska 1"))])),
            EventResponse.Embedded.Event(id: "3", name: "Event one", images: [EventResponse.Embedded.Event.EventImage(ratio: "", url: URL(string: "https://s1.ticketm.net/dam/a/973/68cd0a3e-45cc-49fa-b495-5d779fe71973_TABLET_LANDSCAPE_3_2.jpg")!, width: 500, height: 700)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Warszawska 1"))])),
            EventResponse.Embedded.Event(id: "4", name: "Event one", images: [EventResponse.Embedded.Event.EventImage(ratio: "16_9", url: URL(string: "https://s1.ticketm.net/dam/a/ccd/6856dc30-2cd8-43a9-a842-3f92153f7ccd_TABLET_LANDSCAPE_LARGE_16_9.jpg")!, width: 300, height: 200)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "Sala Koncertowa Radia Wrocław", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Warszawska 1"))])),
            EventResponse.Embedded.Event(id: "5", name: "Event one", images: [EventResponse.Embedded.Event.EventImage(ratio: "16_9", url: URL(string: "https://s1.ticketm.net/dam/a/dd5/d7a9ceee-bde3-4e84-a35f-b257044c4dd5_RECOMENDATION_16_9.jpg")!, width: 300, height: 200), EventResponse.Embedded.Event.EventImage(ratio: "", url: URL(string: "www.w.en/2kjfsaldkjf-sadf-asd-asdf_SOURCE.jpg")!, width: 500, height: 700), EventResponse.Embedded.Event.EventImage(ratio: "", url: URL(string: "www.w.en/2kjfsaldkjf-sadf-asd-fas_RECOMENDATION.jpg")!, width: 100, height: 150)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Warszawska 1"))])),
            EventResponse.Embedded.Event(id: "6", name: "Event one", images: [EventResponse.Embedded.Event.EventImage(ratio: "16_9", url: URL(string: "noURL")!, width: 300, height: 200)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Aleja Karkonoska 10"))])),
            EventResponse.Embedded.Event(id: "7", name: "Event one", images: [EventResponse.Embedded.Event.EventImage(ratio: "", url: URL(string: "https://s1.ticketm.net/dam/a/973/68cd0a3e-45cc-49fa-b495-5d779fe71973_TABLET_LANDSCAPE_3_2.jpg")!, width: 500, height: 700)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Warszawska 1"))])),
            EventResponse.Embedded.Event(id: "8", name: "Event one", images: [EventResponse.Embedded.Event.EventImage(ratio: "16_9", url: URL(string: "https://s1.ticketm.net/dam/a/ccd/6856dc30-2cd8-43a9-a842-3f92153f7ccd_TABLET_LANDSCAPE_LARGE_16_9.jpg")!, width: 300, height: 200)], dates: EventResponse.Embedded.Event.EventDates(start: EventResponse.Embedded.Event.EventDates.EventStart(localDate: "2025-07-18")), embedded: EventResponse.Embedded.Event.EventEmbedded(venues: [EventResponse.Embedded.Event.EventEmbedded.Venue(name: "PGE Narodowy", city: EventResponse.Embedded.Event.EventEmbedded.Venue.City(name: "Warszawa"), address: EventResponse.Embedded.Event.EventEmbedded.Venue.Address(line1: "Juliusza Słowackiego Słowackiego 27"))]))
        ]
    }
}
